import Head from 'next/head';
import Image from 'next/image';
import { Inter, Noto_Sans_KR } from 'next/font/google';
import styles from '@/styles/Home.module.css';
import { Button } from '@/components/common/Button';

const noto = Noto_Sans_KR({
  subsets: ['latin'],
  weight: ['400', '500', '700'],
});

export default function Home() {
  return (
    <>
      <Head>
        <title>Create Next App</title>
        <meta name='description' content='Generated by create next app' />
        <meta name='viewport' content='width=device-width, initial-scale=1' />
        <link rel='icon' href='/favicon.ico' />
      </Head>
      <main className={`${styles.main} ${noto.className}`}>
        <section className={styles.section}>
          <h1>Large Size</h1>
          <div>
            <Button className={noto.className}>Primay Button</Button>
            <Button className={noto.className} color='secondary'>
              Secondary Button
            </Button>
          </div>
        </section>
        <section className={styles.section}>
          <h1>Small Size</h1>
          <div>
            <Button className={noto.className} size='sm'>
              Primay Button
            </Button>
            <Button className={noto.className} color='secondary' size='sm'>
              Secondary Button
            </Button>
          </div>
        </section>
      </main>
    </>
  );
}
